import React from "react";
import AdList from "../components/ad-list/AdList";

const adsMoc = [
    {
        "select": "Перевезення",
        "name": "Петров Іван Сергійович",
        "telephone": "+38099112233",
        "email": "petrov@qwerty.com",
        "city": "Київ",
        "address": "м. Перемоги, 1",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas.",
        "cardnumber": "12345678901234",
        "fullbankname": "GgggMmmmBbbbHhhh Bank",
        "shortbankname": "GMBH Bank",
        "mfo": "8465",
        "iban": "2546542544",
        "edrpou": "12345678",
        "accountnumber": "484654654465454845",
        "instagram": "",
        "telegram": "https://t.me/kolomiiitsev",
        "facebook": "https://www.facebook.com/kolomiiitsev/",
    },
    {
        "select": "Гуманітарна допомога",
        "name": "Олександров Василь Петрович",
        "telephone": "+380669998877",
        "email": "oleksandrov@qwerty.com",
        "city": "Днепр",
        "address": "пр. Свободи, 47/12",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam architecto numquam aliquam quas aspernatur voluptatibus harum non cumque excepturi? Nesciunt reiciendis, autem deleniti debitis asperiores nulla ipsa sapiente doloribus officiis.",
        "cardnumber": "",
        "fullbankname": "",
        "shortbankname": "",
        "mfo": "",
        "iban": "",
        "edrpou": "",
        "accountnumber": "",
        "instagram": "https://www.instagram.com/kolomiiitsev",
        "telegram": "",
        "facebook": "https://www.facebook.com/kolomiiitsev/",
    },
    {
        "select": "Інше",
        "name": "Фомін Віталій Володимирович",
        "telephone": "+380674445566",
        "email": "fomin@qwerty.com",
        "city": "Запоріжжя",
        "address": "",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam architecto numquam aliquam quas aspernatur voluptatibus harum non cumque excepturi? Nesciunt reiciendis, autem deleniti debitis asperiores nulla ipsa sapiente doloribus officiisa nulla ipsa sapiente doloribus officiis qwertyuiopas.",
        "cardnumber": "",
        "fullbankname": "",
        "shortbankname": "",
        "mfo": "",
        "iban": "",
        "edrpou": "",
        "accountnumber": "",
        "instagram": "https://www.instagram.com/kolomiiitsev",
        "telegram": "https://t.me/kolomiiitsev",
        "facebook": "",
    },
    {
        "select": "Гуманітарна допомога",
        "name": "Петров Александр Васильович",
        "telephone": "+380687778899",
        "email": "",
        "city": "Днепр",
        "address": "",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam architecto numquam aliquam quas aspernatur voluptatibus harum non cumque excepturi? Nesciunt reiciendis, autem deleniti debitis asperiores nulla ipsa sapiente doloribus officiis.",
        "cardnumber": "43219876543210",
        "fullbankname": "",
        "shortbankname": "",
        "mfo": "8465",
        "iban": "2546542544",
        "edrpou": "0123456789",
        "accountnumber": "484654654465454845",
        "instagram": "https://www.instagram.com/kolomiiitsev",
        "telegram": "https://t.me/kolomiiitsev",
        "facebook": "https://www.facebook.com/kolomiiitsev/",
    },
    {
        "select": "Медицина",
        "name": "Дубровський Георгій В'ячеславович",
        "telephone": "+380633211221",
        "email": "heorhii@qwerty.com",
        "city": "Хмельницький",
        "address": "мм. Квітневий, 27/80",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam architecto numquam aliquam quas aspernatur voluptatibus harum non cumque excepturi? Nesciunt reiciendis, autem deleniti debitis asperiores nulla ipsa sapiente doloribus officiisa nulla ipsa sapiente doloribus officiis qwertyuiopas.",
        "cardnumber": "12345678",
        "fullbankname": "йфяцічувскамепинртгоьшлбщд",
        "shortbankname": "йфяцічусскам",
        "mfo": "123456566654546",
        "iban": "64654654465465465465",
        "edrpou": "0123456789",
        "accountnumber": "апу65+5+65ппукпук5п565пку546",
        "instagram": "https://www.instagram.com/kolomiiitsev",
        "telegram": "https://t.me/kolomiiitsev",
        "facebook": "https://www.facebook.com/kolomiiitsev/",
    },
    {
        "select": "Ліки",
        "name": "Дубровський Георгій В'ячеславович",
        "telephone": "+380633211221",
        "email": "heorhii@qwerty.com",
        "city": "Хмельницький",
        "address": "мм. Квітневий, 27/80",
        "text": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam sit ipsum neque. Tempore totam velit veniam eius a deleniti excepturi tenetur unde alias sunt quia aliquid, placeat aperiam odio voluptas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam architecto numquam aliquam quas aspernatur voluptatibus harum non cumque excepturi? Nesciunt reiciendis, autem deleniti debitis asperiores nulla ipsa sapiente doloribus officiisa nulla ipsa sapiente doloribus officiis qwertyuiopas.",
        "cardnumber": "12345678",
        "fullbankname": "йфяцічувскамепинртгоьшлбщд",
        "shortbankname": "йфяцічусскам",
        "mfo": "123456566654546",
        "iban": "64654654465465465465",
        "edrpou": "0123456789",
        "accountnumber": "апу65+5+65ппукпук5п565пку546",
        "instagram": "https://www.instagram.com/kolomiiitsev",
        "telegram": "https://t.me/kolomiiitsev",
        "facebook": "https://www.facebook.com/kolomiiitsev/",
    }
]

export const VolunteerContainer = () => {
    return (<AdList id={0} ads={adsMoc} numberAdsOfPages={0}/>)
}
